#!/usr/bin/env bash
# Pings an IP address passed an argument 5 times.

IP="${1}"

fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
